services:

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto

    ports:
      - "1883:1883"

    volumes:
      - ./mosquitto:/mosquitto/config

    restart: unless-stopped

  homeassistant:
    image: homeassistant/home-assistant:stable
    container_name: homeassistant

    ports:
      - "8123:8123"

    volumes:
      - ./homeassistant:/config

    restart: unless-stopped